---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: rancher-github-token
spec:
  externalSecretName: rancher-github-token
  externalSecretSpec:
    data:
    - remoteRef:
        key: secret/rancherbot/rancher/credentials
      secretKey: credentials
    refreshInterval: 1m
    secretStoreRef:
      kind: ClusterSecretStore
      name: vault
    target:
      name: rancher-github-token
  namespaces:
  - github-org-rancher
  - upbound-system
  refreshTime: 1m
