---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: rancher-eio-github-token
spec:
  externalSecretName: rancher-eio-github-token
  externalSecretSpec:
    data:
    - remoteRef:
        key: secret/rancherbot/rancher-eio/credentials
      secretKey: credentials
    refreshInterval: 1m
    secretStoreRef:
      kind: ClusterSecretStore
      name: vault
    target:
      name: rancher-eio-github-token
  namespaces:
  - rancher-eio-github-org
  - upbound-system
  - backstage
  refreshTime: 1m
