---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: rancher-eio-github-token
spec:
  externalSecretName: rancher-eio-github-token
  externalSecretSpec:
    target:
      name: rancher-eio-github-token
      template:
        data:
          credentials: "{\"token\":\"{{  .token }}\",\"owner\":\"{{ .owner }}\"}"
    data:
    - remoteRef:
        key: secret/rancher-eio-github-token/credentials
        property: owner
      secretKey: owner
    - remoteRef:
        key: secret/rancher-eio-github-token/credentials
        property: token
      secretKey: token
    refreshInterval: 1m
    secretStoreRef:
      kind: ClusterSecretStore
      name: vault
  namespaces:
  - rancher-eio-github-org
  - upbound-system
  refreshTime: 1m
