---
apiVersion: github.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: rancher
spec:
  credentials:
    secretRef:
      key: credentials
      name: rancher-github-token
      namespace: upbound-system
    source: Secret
