apiVersion: enterprise.github.upbound.io/v1alpha1
kind: OrganizationRuleset
metadata:
  name: rancher-default-ruleset
spec:
  providerConfigRef:
    name: rancher
  deletionPolicy: Orphan
  forProvider:
    name: "rancher-default-ruleset"
    enforcement: "evaluate"
    target: "branch"
    conditions:
      - refName:
          - include:
              - "~DEFAULT_BRANCH"
            exclude: []
        repositoryName:
          - include:
              - "*"
            exclude:
              - "eio*"
              - "product-docs-playbook"
              - "support-bundle-kit"
              - "elemental*"
            protected: false
    rules:
      - deletion: true
        nonFastForward: true
        pullRequest:
          - requiredApprovingReviewCount: 1
            dismissStaleReviewsOnPush: false
            requireCodeOwnerReview: false
            requireLastPushApproval: false
            requiredReviewThreadResolution: false
    bypassActors:
      - actorId: 0
        actorType: "EnterpriseOwner"
        bypassMode: "always"
      - actorId: 0
        actorType: "OrganizationAdmin"
        bypassMode: "always"
      - actorId: 5
        actorType: "RepositoryRole"
        bypassMode: "always"
      - actorId: 29110
        actorType: "Integration"
        bypassMode: "always"
      - actorId: 269045
        actorType: "Integration"
        bypassMode: "always"
      - actorId: 681210
        actorType: "Integration"
        bypassMode: "always"
      - actorId: 860038
        actorType: "Integration"
        bypassMode: "always"
      - actorId: 882665
        actorType: "Integration"
        bypassMode: "always"
      - actorId: 979954
        actorType: "Integration"
        bypassMode: "always"
      - actorId: 989984
        actorType: "Integration"
        bypassMode: "always"
      - actorId: 999757
        actorType: "Integration"
        bypassMode: "always"
      - actorId: 1010174
        actorType: "Integration"
        bypassMode: "always"
      - actorId: 1127151
        actorType: "Integration"
        bypassMode: "always"
      - actorId: 1087529
        actorType: "Team"
        bypassMode: "always"
      - actorId: 5837354
        actorType: "Team"
        bypassMode: "always"
      - actorId: 6332922
        actorType: "Team"
        bypassMode: "always"
      - actorId: 6567330
        actorType: "Team"
        bypassMode: "always"
