apiVersion: enterprise.github.upbound.io/v1alpha1
kind: OrganizationRuleset
metadata:
  name: rancher-default-ruleset-test
spec:
  providerConfigRef:
    name: rancher
  deletionPolicy: Orphan
  forProvider:
    name: "rancher-default-test"
    enforcement: "evaluate"
    target: "branch"
    conditions:
      - refName:
          - include:
              - "~DEFAULT_BRANCH"
            exclude: []
        repositoryName:
          - include:
              - "*"
            exclude:
              - "eio*"
              - "security-team"
              - "product-docs-playbook"
              - "support-bundle-kit"
              - "elemental*"
            protected: false
    rules:
      - deletion: true
        nonFastForward: true
        pullRequest:
          - requiredApprovingReviewCount: 2
            dismissStaleReviewsOnPush: false
            requireCodeOwnerReview: false
            requireLastPushApproval: false
            requiredReviewThreadResolution: false
    bypassActors:
      - actorId: 0
        actorType: "EnterpriseOwner"
        bypassMode: "always"
      - actorId: 0
        actorType: "OrganizationAdmin"
        bypassMode: "always"
      - actorId: 1087529
        actorType: "Team"
        bypassMode: "always"
      - actorId: 5837354
        actorType: "Team"
        bypassMode: "always"
      - actorId: 6332922
        actorType: "Team"
        bypassMode: "always"
      - actorId: 6567330
        actorType: "Team"
        bypassMode: "always"
